# Generated by Django 4.1.2 on 2022-10-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, unique=True)),
                ('parameter_value', models.CharField(max_length=100)),
                ('parameter_active', models.BooleanField(default=False)),
                ('parameter_description', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Jewl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, null=True), null=True)),
                ('description', models.TextField(default='', max_length=400, null=True)),
                ('remarks', models.TextField(default='', max_length=400, null=True)),
                ('jewl_id', models.CharField(max_length=10, null=True, unique=True)),
                ('issue_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('kundan_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['jewl_id'],
            },
        ),
        migrations.CreateModel(
            name='JewlStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=400, null=True)),
                ('remarks', models.TextField(default='', max_length=400, null=True)),
                ('stage', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JewlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=400, null=True)),
                ('remarks', models.TextField(default='', max_length=400, null=True)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, null=True), null=True)),
                ('description', models.TextField(default='', max_length=400, null=True)),
                ('remarks', models.TextField(default='', max_length=400, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('is_credit', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, null=True), null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100, null=True)),
                ('last_name', models.CharField(default='', max_length=100, null=True)),
                ('nick_name', models.CharField(default=models.CharField(blank=True, default='', max_length=100), max_length=100)),
                ('profile_pic', models.CharField(default='', max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('worker_type', models.CharField(choices=[('Jadai', 'Jadai'), ('Ghat', 'Ghat')], default='Jadai', max_length=10)),
                ('acceptance_count', models.IntegerField(blank=True, default=0, null=True)),
                ('rejection_count', models.IntegerField(blank=True, default=0, null=True)),
                ('current_count', models.IntegerField(blank=True, default=0, null=True)),
                ('pending_count', models.IntegerField(blank=True, default=0, null=True)),
                ('completed_count', models.IntegerField(blank=True, default=0, null=True)),
                ('current_metal_amount', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('total_metal_count', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JewlStageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, null=True), null=True)),
                ('description', models.TextField(default='', max_length=400, null=True)),
                ('remarks', models.TextField(default='', max_length=400, null=True)),
                ('expected_finish_date_time', models.DateTimeField(blank=True, null=True)),
                ('actual_finish_date_time', models.DateTimeField(blank=True, null=True)),
                ('jewl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewl')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewlstage')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JewlImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, null=True), null=True)),
                ('image_url', models.CharField(max_length=300, null=True)),
                ('jewl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewl')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewlstage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jewl',
            name='jewl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewltype'),
        ),
        migrations.AddField(
            model_name='jewl',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jewlstage'),
        ),
    ]
