# Generated by Django 4.1.2 on 2022-10-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewlstagetransaction',
            name='actual_finish_date_time',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='acceptance_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='completed_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='current_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='current_metal_amount',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='pending_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='rejection_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='total_metal_count',
        ),
        migrations.AddField(
            model_name='jewltype',
            name='type_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jewltype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='WorkerStoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond', models.IntegerField(blank=True, max_length=10, null=True)),
                ('navratna', models.IntegerField(blank=True, max_length=10, null=True)),
                ('pink_ruby', models.IntegerField(blank=True, max_length=10, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_count', models.IntegerField(blank=True, default=0, null=True)),
                ('rejection_count', models.IntegerField(blank=True, default=0, null=True)),
                ('current_count', models.IntegerField(blank=True, default=0, null=True)),
                ('pending_count', models.IntegerField(blank=True, default=0, null=True)),
                ('completed_count', models.IntegerField(blank=True, default=0, null=True)),
                ('current_metal_amount', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('total_metal_count', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
        ),
    ]
