# Generated by Django 4.1.2 on 2022-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_jewlstagetransaction_actual_finish_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstonerate',
            name='diamond',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerstonerate',
            name='navratna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerstonerate',
            name='pink_ruby',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
