# Generated by Django 4.1.2 on 2022-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workerstonerate_diamond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewl',
            name='last_updated_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewlimage',
            name='last_updated_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewlstagetransaction',
            name='last_updated_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='last_updated_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_updated_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
