# Generated by Django 4.1.2 on 2022-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jewl_last_updated_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('Jadai', 'Jadai'), ('Ghaat', 'Ghaat')], default='Jadai', max_length=10),
        ),
    ]
