# Generated by Django 4.1.2 on 2022-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_worker_worker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('jadai', 'jadai'), ('ghaat', 'ghaat')], default='Jadai', max_length=10),
        ),
    ]
